### ISSUE TITLE
Assessment Feedback

### ISSUE THREAD

**Issue by timomitchel** [kimalajoy/mod_0_skills#1]
Hey Kimala! Good Job on the assessment! We want you to make a few changes before we deem this `technical ready`

- I would be more specific in the `count` method and name it `specificCount` or `typeCount`. 
- `numOfChairs` seems to represent `totalChairs`, which could be a better name. 
- [x] All my methods are verbs
- [x] My classes are named singularly
- [x] My attribute values represent their data-types. (strings have quotes, etc)
- [x] The methods in my object files clearly represent the change that happened to a specific attribute. (We want to see more than just their new value, how did this value get set?)

Let us know if you have questions! Please make these changes by end of day Sunday! Thanks Kimala.

**Comment by kimalajoy** [comment]
Made requested updates!
